/* 
This file is auto generated by pgx.

The ordering of items is not stable, it is driven by a dependency graph.
*/

-- src/lib.rs:17
-- vector_search::Vector
CREATE TYPE Vector;

-- src/lib.rs:17
-- vector_search::vector_in
CREATE OR REPLACE FUNCTION "vector_in"(
	"input" cstring /* &cstr_core::CStr */
) RETURNS Vector /* vector_search::Vector */
IMMUTABLE PARALLEL SAFE STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'vector_in_wrapper';

-- src/lib.rs:17
-- vector_search::vector_out
CREATE OR REPLACE FUNCTION "vector_out"(
	"input" Vector /* vector_search::Vector */
) RETURNS cstring /* &cstr_core::CStr */
IMMUTABLE PARALLEL SAFE STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'vector_out_wrapper';

-- src/lib.rs:17
-- vector_search::Vector
CREATE TYPE Vector (
	INTERNALLENGTH = variable,
	INPUT = vector_in, /* vector_search::vector_in */
	OUTPUT = vector_out, /* vector_search::vector_out */
	STORAGE = extended
);

-- src/lib.rs:20
-- vector_search::vector_ne
CREATE OR REPLACE FUNCTION "vector_ne"(
	"left" Vector, /* vector_search::Vector */
	"right" Vector /* vector_search::Vector */
) RETURNS bool /* bool */
IMMUTABLE PARALLEL SAFE STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'vector_ne_wrapper';

-- src/lib.rs:20
-- vector_search::vector_ne
CREATE OPERATOR <> (
	PROCEDURE="vector_ne",
	LEFTARG=Vector, /* vector_search::Vector */
	RIGHTARG=Vector, /* vector_search::Vector */
	NEGATOR = =,
	RESTRICT = neqsel,
	JOIN = neqjoinsel
);

-- src/lib.rs:20
-- vector_search::vector_eq
CREATE OR REPLACE FUNCTION "vector_eq"(
	"left" Vector, /* vector_search::Vector */
	"right" Vector /* vector_search::Vector */
) RETURNS bool /* bool */
IMMUTABLE PARALLEL SAFE STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'vector_eq_wrapper';

-- src/lib.rs:20
-- vector_search::vector_eq
CREATE OPERATOR = (
	PROCEDURE="vector_eq",
	LEFTARG=Vector, /* vector_search::Vector */
	RIGHTARG=Vector, /* vector_search::Vector */
	NEGATOR = <>,
	RESTRICT = eqsel,
	JOIN = eqjoinsel,
	HASHES,
	MERGES
);

-- src/lib.rs:59
-- vector_search::l2
CREATE OR REPLACE FUNCTION "l2"(
	"v1" Vector, /* vector_search::Vector */
	"v2" Vector /* vector_search::Vector */
) RETURNS real /* f32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'l2_wrapper';
